name: Colibrí Agents

on:
  workflow_dispatch:
    inputs:
      agent:
        description: "Agent(s) to run from ai/agents/manifest.json (comma-separated). Use 'all' for the full catalog."
        required: false
        default: "all"
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-agents:
    uses: ./ai/.github/workflows/agents.yml
    with:
      agent: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.agent || '' }}
    secrets: inherit
